services:
  postgresql:
    container_name: rs_java_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: trinhvu
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - rs-net
    restart: unless-stopped

  pgadmin:
    container_name: rs_java_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - rs-net
    restart: unless-stopped

  zipkin:
    container_name: rs_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - rs-net

  mongodb:
    image: mongo
    container_name: rs_java_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=trinhvu
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - rs-net

  mongo-express:
    image: mongo-express
    container_name: rs_java_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=trinhvu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - rs-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: rs_java_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - rs-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: rs_java_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - rs-net

  mail-dev:
    container_name: rs_java_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: rs-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - rs-net

  keycloak:
    container_name: rs_keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - rs-net
    command:
      - "start-dev"
networks:
  rs-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: