spring:
  application:
    name: backoffice-bff
  threads:
    virtual:
      enabled: true
#  data:
#    redis:xx
#      host: localhost
#      port: 6379
  session:
    store-type: redis
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF
            scope: openid, profile, email, roles
  cloud:
    gateway:
      routes:
        - id: location_service
          uri: http://localhost:8020
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
server:
  port: 8087
