spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/st
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9098/realms/stock-watch
#        registration:
#          api-client:
#            provider: keycloak
#            client-id: stock-watch-api
#            client-secret: 9sJAzYqZy6hUf2lIK1JrMaCYDNS7WEGF
#            scope: openid, profile, email, roles
#            redirect-uri: *
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: stock-service
          uri: lb:http://STOCK-SERVICE
          predicates:
            - Path=/api/v1/stocks/**
        - id: stock-price-service
          uri: lb:http://STOCK-SERVICE
          predicates:
            - Path=/api/v1/stock-price/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-service-checkouts
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/checkouts/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
#        - id: websocket
#          uri: lb://STOCK-SERVICE
#          predicates:
#            - Path=/ws-stock-updates
#          filters:
#            - StripPrefix=1
server:
  port: 8222
