spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location
    username: trinhvu
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8020
  servlet:
    context-path: /location

springdoc:
  packagesToScan: com.trinhvu.location