spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/st
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: trinhvu
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.trinhvu.order.viewmodel.order.OrderConfirmation
server:
  port: 8060

application:
  config:
    stock-url: http://localhost:8222/api/v1/stocks
    payment-url: http://localhost:8222/api/v1/payments
    cart-url: http://localhost:8222/api/v1/carts
    customer-url: http://localhost:8222/api/v1/customers

resilience4j:
  retry:
    instances:
      rest-api:
        max-attempts: 3

  circuitbreaker:
    instances:
      rest-circuit-breaker:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3