spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: trinhvu
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: stocksGetVm:com.trinhvu.stock.viewmodel.stock.StocksGetVm, stocksPriceGetVm:com.trinhvu.stock.viewmodel.stock.StocksPriceGetVm, BinanceStockGetVm:com.trinhvu.stock.viewmodel.binanceStock.BinanceStockGetVm
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: stocksPriceGetVm:com.trinhvu.stock.viewmodel.stock.StocksPriceGetVm, BinanceStockGetVm:com.trinhvu.stock.viewmodel.binanceStock.BinanceStockGetVm
  redis:
    host: localhost
    port: 6379
server:
  port: 8050