spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks
    username: trinhvu
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050

application:
  config:
    stock-url: https://api.polygon.io/v3/reference/tickers
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments