spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/st

server:
  servlet:
    context-path: /common-library

cors:
  allowed-origins: "*"